<?php

declare(strict_types=1);

return [
    'QUIZ_HERO_DB_HOST' => 'rdbms.strato.de',
    'QUIZ_HERO_DB_PORT' => '3306',
    'QUIZ_HERO_DB_NAME' => 'DB_NAME',
    'QUIZ_HERO_DB_USER' => 'DB_USER',
    'QUIZ_HERO_DB_PASSWORD' => 'DB_PASSWORD',
    'QUIZ_HERO_ADMIN_USER' => 'admin',
    'QUIZ_HERO_ADMIN_PASSWORD_HASH' => 'PASSWORD_HASH',
    'QUIZ_HERO_USER_TOKEN_SECRET' => 'LONG_RANDOM_SECRET',
    'QUIZ_HERO_SEO_EXPORT_TOKEN' => 'LONG_RANDOM_SEO_EXPORT_TOKEN',
];
